version: '3'
services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    ports:
      - 27017:27017
    environment:
      MONGODB_USER: "admin"
      MONGODB_DATABASE: "netconnect"
      MONGODB_PASS: "1234"
    volumes:
      - type: bind
        source: ./data
        target: /data/db